spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_ENDPOINT_URL}:3306/${DATABASE_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  sql:
    init:
      mode: never

  config:
    import: optional:application-secret.properties
    activate:
      on-profile: local

  mybatis:
    config-location: classpath:mybatis-config-mysql.xml
    mapper-locations: classpath:mappers/mysql/main/*/*.xml