spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_ENDPOINT_URL}:3306/${DATABASE_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  data:
    mongodb:
      uri: ${MONGO_DB_URI}
      port: 27017

  sql:
    init:
      mode: never

  config:
    import: optional:application-secret.properties
    activate:
      on-profile: local

  mybatis:
    config-location: classpath:mybatis/config/mybatis-config-mysql.xml
    mapper-locations: classpath:mybatis/mappers/mysql/main/*/*.xml

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: sensor-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      allow:
        auto:
          create:
            topics: false
      group:
        instance:
          id: sensor-instance-1
    listener:
      ack-mode: MANUAL_IMMEDIATE
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
